#include "esm/query.hpp"
#include <windows.h>
#include <algorithm>
#include <cwctype>
#include <limits>
#include <string>
#include <vector>
namespace esm {
namespace {
bool starts_with(std::wstring_view value,std::wstring_view prefix){return value.size()>=prefix.size()&&value.substr(0,prefix.size())==prefix;}
bool truthy(std::wstring_view value,bool& result){auto v=fold_case(value);if(v==L"1"||v==L"yes"||v==L"true"||v==L"on"){result=true;return true;}if(v==L"0"||v==L"no"||v==L"false"||v==L"off"){result=false;return true;}return false;}
struct Lexeme { enum class Kind { word,left,right,and_op,or_op,not_op } kind{Kind::word}; std::wstring text; };
std::vector<Lexeme> tokenize(std::wstring_view input,bool& ok,std::wstring& error){
    std::vector<Lexeme> out;std::wstring current;bool quote=false;
    auto flush=[&]{if(current.empty())return;auto folded=fold_case(current);Lexeme::Kind kind=Lexeme::Kind::word;if(folded==L"and"||current==L"&&")kind=Lexeme::Kind::and_op;else if(folded==L"or"||current==L"||")kind=Lexeme::Kind::or_op;else if(folded==L"not"||current==L"!")kind=Lexeme::Kind::not_op;out.push_back({kind,std::move(current)});current.clear();};
    for(std::size_t i=0;i<input.size();++i){wchar_t ch=input[i];if(ch==L'"'){quote=!quote;continue;}if(!quote&&(std::iswspace(ch)||ch==L'('||ch==L')')){flush();if(ch==L'(')out.push_back({Lexeme::Kind::left,{}});else if(ch==L')')out.push_back({Lexeme::Kind::right,{}});continue;}if(!quote&&ch==L'!'&&current.empty()){if(i+1<input.size()&&!std::iswspace(input[i+1])&&input[i+1]!=L'('&&input[i+1]!=L')'){current.push_back(ch);continue;}flush();out.push_back({Lexeme::Kind::not_op,{}});continue;}if(ch==L'\\'&&i+1<input.size()&&input[i+1]==L'"'){current.push_back(L'"');++i;continue;}current.push_back(ch);}
    if(quote){ok=false;error=L"unterminated quote";return {};}flush();return out;
}
bool parse_unsigned(std::wstring_view text,std::uint64_t& value){if(text.empty())return false;value=0;for(wchar_t ch:text){if(ch<L'0'||ch>L'9')return false;auto digit=(std::uint64_t)(ch-L'0');if(value>(std::numeric_limits<std::uint64_t>::max()-digit)/10)return false;value=value*10+digit;}return true;}
bool split_comparison(std::wstring_view value,NumericComparison& comparison,std::wstring_view& rest){comparison=NumericComparison::equal;if(starts_with(value,L">=")){comparison=NumericComparison::greater_equal;rest=value.substr(2);}else if(starts_with(value,L"<=")){comparison=NumericComparison::less_equal;rest=value.substr(2);}else if(starts_with(value,L">") ){comparison=NumericComparison::greater;rest=value.substr(1);}else if(starts_with(value,L"<")){comparison=NumericComparison::less;rest=value.substr(1);}else if(starts_with(value,L"=")){rest=value.substr(1);}else rest=value;return !rest.empty();}
bool parse_size(std::wstring_view input,std::uint64_t& bytes){auto folded=fold_case(input);std::size_t number_end=0;while(number_end<folded.size()&&folded[number_end]>=L'0'&&folded[number_end]<=L'9')++number_end;if(number_end==0)return false;std::uint64_t number{};if(!parse_unsigned(std::wstring_view(folded).substr(0,number_end),number))return false;auto unit=std::wstring_view(folded).substr(number_end);std::uint64_t multiplier=1;if(unit.empty()||unit==L"b")multiplier=1;else if(unit==L"k"||unit==L"kb"||unit==L"kib")multiplier=1024ULL;else if(unit==L"m"||unit==L"mb"||unit==L"mib")multiplier=1024ULL*1024;else if(unit==L"g"||unit==L"gb"||unit==L"gib")multiplier=1024ULL*1024*1024;else if(unit==L"t"||unit==L"tb"||unit==L"tib")multiplier=1024ULL*1024*1024*1024;else return false;if(number>std::numeric_limits<std::uint64_t>::max()/multiplier)return false;bytes=number*multiplier;return true;}
bool parse_date(std::wstring_view input,std::uint64_t& value){SYSTEMTIME st{};if(input.size()<10||input[4]!=L'-'||input[7]!=L'-')return false;std::uint64_t y{},m{},d{};if(!parse_unsigned(input.substr(0,4),y)||!parse_unsigned(input.substr(5,2),m)||!parse_unsigned(input.substr(8,2),d))return false;st.wYear=(WORD)y;st.wMonth=(WORD)m;st.wDay=(WORD)d;if(input.size()>10){if(input.size()<16||(input[10]!=L'T'&&input[10]!=L' ')||input[13]!=L':')return false;std::uint64_t hour{},minute{};if(!parse_unsigned(input.substr(11,2),hour)||!parse_unsigned(input.substr(14,2),minute))return false;st.wHour=(WORD)hour;st.wMinute=(WORD)minute;}FILETIME local{},utc{};if(!SystemTimeToFileTime(&st,&local))return false;if(!LocalFileTimeToFileTime(&local,&utc))utc=local;value=(std::uint64_t(utc.dwHighDateTime)<<32U)|utc.dwLowDateTime;return true;}
std::uint32_t attribute_flag(std::wstring_view name){auto v=fold_case(name);if(v==L"readonly"||v==L"ro")return FILE_ATTRIBUTE_READONLY;if(v==L"hidden"||v==L"h")return FILE_ATTRIBUTE_HIDDEN;if(v==L"system"||v==L"s")return FILE_ATTRIBUTE_SYSTEM;if(v==L"archive"||v==L"a")return FILE_ATTRIBUTE_ARCHIVE;if(v==L"compressed"||v==L"c")return FILE_ATTRIBUTE_COMPRESSED;if(v==L"encrypted"||v==L"e")return FILE_ATTRIBUTE_ENCRYPTED;if(v==L"offline"||v==L"o")return FILE_ATTRIBUTE_OFFLINE;if(v==L"reparse"||v==L"junction"||v==L"symlink")return FILE_ATTRIBUTE_REPARSE_POINT;return 0;}
int precedence(Lexeme::Kind kind){if(kind==Lexeme::Kind::not_op)return 3;if(kind==Lexeme::Kind::and_op)return 2;if(kind==Lexeme::Kind::or_op)return 1;return 0;}
QueryOpcode opcode(Lexeme::Kind kind){if(kind==Lexeme::Kind::not_op)return QueryOpcode::logical_not;if(kind==Lexeme::Kind::or_op)return QueryOpcode::logical_or;return QueryOpcode::logical_and;}
struct ParsedWord { bool directive{}; QueryTerm term; };
ParsedWord parse_word(std::wstring token,ParsedQuery& query){ParsedWord result;if(!token.empty()&&token.front()==L'!'){result.term.excluded=true;token.erase(token.begin());}auto folded=fold_case(token);bool flag{};
    if(folded==L"file:"||folded==L"files:"){query.directories_only=false;result.directive=true;return result;}if(folded==L"folder:"||folded==L"dir:"){query.directories_only=true;result.directive=true;return result;}
    if(starts_with(folded,L"case:")){if(!truthy(std::wstring_view(token).substr(5),flag)){query.valid=false;query.error=L"invalid case option";}else query.case_sensitive=flag;result.directive=true;return result;}
    if(starts_with(folded,L"wholeword:")){if(!truthy(std::wstring_view(token).substr(10),flag)){query.valid=false;query.error=L"invalid whole-word option";}else query.whole_word=flag;result.directive=true;return result;}
    if(starts_with(folded,L"dupe:")){auto mode=folded.substr(5);if(mode==L"name")query.duplicate_mode=DuplicateMode::name;else if(mode==L"size")query.duplicate_mode=DuplicateMode::size;else if(mode==L"name-size"||mode==L"name_size")query.duplicate_mode=DuplicateMode::name_and_size;else{query.valid=false;query.error=L"invalid duplicate mode";}result.directive=true;return result;}
    auto scoped=[&](std::wstring_view prefix,MatchTarget target){if(!starts_with(folded,prefix))return false;result.term.target=target;result.term.value=token.substr(prefix.size());return true;};
    if(scoped(L"name:",MatchTarget::name)||scoped(L"path:",MatchTarget::path)||scoped(L"ext:",MatchTarget::extension)){}
    else if(scoped(L"regex:",MatchTarget::any)){result.term.regex=true;}
    else if(scoped(L"name-regex:",MatchTarget::name)){result.term.regex=true;}
    else if(scoped(L"path-regex:",MatchTarget::path)){result.term.regex=true;}
    else if(starts_with(folded,L"size:")){result.term.target=MatchTarget::size;std::wstring_view rest;if(!split_comparison(std::wstring_view(token).substr(5),result.term.comparison,rest)||!parse_size(rest,result.term.numeric_value)){query.valid=false;query.error=L"invalid size expression";}return result;}
    else if(starts_with(folded,L"date:")||starts_with(folded,L"dm:")||starts_with(folded,L"modified:")){std::size_t offset=starts_with(folded,L"date:")?5:(starts_with(folded,L"dm:")?3:9);result.term.target=MatchTarget::last_write_time;std::wstring_view rest;if(!split_comparison(std::wstring_view(token).substr(offset),result.term.comparison,rest)||!parse_date(rest,result.term.numeric_value)){query.valid=false;query.error=L"invalid date expression";}return result;}
    else if(starts_with(folded,L"attr:")||starts_with(folded,L"attrib:")){std::size_t offset=starts_with(folded,L"attr:")?5:7;auto value=std::wstring_view(token).substr(offset);if(!value.empty()&&value.front()==L'!'){result.term.attribute_absent=true;value.remove_prefix(1);}result.term.target=MatchTarget::attributes;std::size_t start=0;while(start<=value.size()){auto comma=value.find(L',',start);auto part=value.substr(start,comma==std::wstring_view::npos?value.size()-start:comma-start);auto bit=attribute_flag(part);if(!bit){query.valid=false;query.error=L"invalid attribute name";break;}result.term.attribute_mask|=bit;if(comma==std::wstring_view::npos)break;start=comma+1;}return result;}
    else {result.term.target=MatchTarget::any;result.term.value=std::move(token);}
    if(result.term.target==MatchTarget::extension&&!result.term.value.empty()&&result.term.value.front()==L'.')result.term.value.erase(result.term.value.begin());
    if(result.term.value.empty()){query.valid=false;query.error=L"empty scoped query term";}result.term.wildcard=result.term.value.find_first_of(L"*?")!=std::wstring::npos;return result;
}
}
std::wstring fold_case(std::wstring_view text){std::wstring result;result.reserve(text.size());for(wchar_t ch:text)result.push_back((wchar_t)std::towlower(ch));return result;}
ParsedQuery parse_query(std::wstring_view input){ParsedQuery query;bool lex_ok=true;auto tokens=tokenize(input,lex_ok,query.error);if(!lex_ok){query.valid=false;return query;}std::vector<Lexeme::Kind> operators;bool have_operand=false;bool expect_operand=true;
    auto emit_operator=[&](Lexeme::Kind kind){query.program.push_back({opcode(kind),0});};
    auto push_operator=[&](Lexeme::Kind kind){while(!operators.empty()&&operators.back()!=Lexeme::Kind::left&&precedence(operators.back())>=precedence(kind)){emit_operator(operators.back());operators.pop_back();}operators.push_back(kind);};
    for(auto& token:tokens){if(token.kind==Lexeme::Kind::word){auto parsed=parse_word(std::move(token.text),query);if(!query.valid)return query;if(parsed.directive)continue;if(!expect_operand)push_operator(Lexeme::Kind::and_op);query.terms.push_back(std::move(parsed.term));query.program.push_back({QueryOpcode::term,query.terms.size()-1});if(query.terms.back().excluded)query.program.push_back({QueryOpcode::logical_not,0});have_operand=true;expect_operand=false;continue;}
        if(token.kind==Lexeme::Kind::left){if(!expect_operand)push_operator(Lexeme::Kind::and_op);operators.push_back(token.kind);expect_operand=true;continue;}
        if(token.kind==Lexeme::Kind::right){if(expect_operand){query.valid=false;query.error=L"unexpected closing parenthesis";return query;}bool found=false;while(!operators.empty()){auto top=operators.back();operators.pop_back();if(top==Lexeme::Kind::left){found=true;break;}emit_operator(top);}if(!found){query.valid=false;query.error=L"unmatched closing parenthesis";return query;}expect_operand=false;continue;}
        if(token.kind==Lexeme::Kind::not_op){if(!expect_operand)push_operator(Lexeme::Kind::and_op);operators.push_back(token.kind);expect_operand=true;continue;}
        if(expect_operand){query.valid=false;query.error=L"binary operator without left operand";return query;}push_operator(token.kind);expect_operand=true;
    }
    if(have_operand&&expect_operand){query.valid=false;query.error=L"query ends with an operator";return query;}while(!operators.empty()){auto top=operators.back();operators.pop_back();if(top==Lexeme::Kind::left){query.valid=false;query.error=L"unmatched opening parenthesis";return query;}emit_operator(top);}return query;
}
bool wildcard_match(std::wstring_view pattern,std::wstring_view value){std::size_t p=0,v=0,star=std::wstring_view::npos,checkpoint=0;while(v<value.size()){if(p<pattern.size()&&(pattern[p]==L'?'||pattern[p]==value[v])){++p;++v;}else if(p<pattern.size()&&pattern[p]==L'*'){star=p++;checkpoint=v;}else if(star!=std::wstring_view::npos){p=star+1;v=++checkpoint;}else return false;}while(p<pattern.size()&&pattern[p]==L'*')++p;return p==pattern.size();}
int natural_compare(std::wstring_view left,std::wstring_view right,bool sensitive){std::size_t a=0,b=0;while(a<left.size()&&b<right.size()){if(std::iswdigit(left[a])&&std::iswdigit(right[b])){std::size_t ae=a,be=b;while(ae<left.size()&&left[ae]==L'0')++ae;while(be<right.size()&&right[be]==L'0')++be;std::size_t ax=ae,bx=be;while(ax<left.size()&&std::iswdigit(left[ax]))++ax;while(bx<right.size()&&std::iswdigit(right[bx]))++bx;auto al=ax-ae,bl=bx-be;if(al!=bl)return al<bl?-1:1;for(std::size_t i=0;i<al;++i)if(left[ae+i]!=right[be+i])return left[ae+i]<right[be+i]?-1:1;std::size_t ar=ax-a,br=bx-b;if(ar!=br)return ar<br?-1:1;a=ax;b=bx;continue;}wchar_t ac=sensitive?left[a]:(wchar_t)std::towlower(left[a]);wchar_t bc=sensitive?right[b]:(wchar_t)std::towlower(right[b]);if(ac!=bc)return ac<bc?-1:1;++a;++b;}if(a==left.size()&&b==right.size())return 0;return a==left.size()?-1:1;}
}
